### ISSUE TITLE
.NET Framework version out of support

### ISSUE THREAD

**Issue by imnasnainaec** [hatton/FileMeddler#2]
The FileMeddler is on `<TargetFrameworkVersion>v4.5.2</TargetFrameworkVersion>`, which reached end of support in April 2022. Is there any plan to update to a [supported version](https://dotnet.microsoft.com/en-us/download/visual-studio-sdks?cid=msbuild-developerpacks#supported-versions-framework)?

**Comment by hatton** [comment]
There isn't. Is this causing a problem for you?

**Comment by imnasnainaec** [comment]
Not yet. I'm wanting to try it out and am downloading the v4.5.2 Developer Pack now.

**Comment by hatton** [comment]
I'd be surprised if you need to download anything other than File Meddler. Just run it.

**Comment by imnasnainaec** [comment]
I don't see an executable, so I was trying to build it.

**Comment by andrew-polk** [comment]
I'm sending you a direct link to the exe we are using currently.

**Comment by imnasnainaec** [comment]
Cool, thanks! I was also able to get it to build after installing 4.5.2.

**Comment by hatton** [comment]
Releases are here: https://github.com/hatton/FileMeddler/releases/

**Comment by imnasnainaec** [comment]
Ah, makes sense. Thank you, @hatton.
